import { Vazirmatn } from "next/font/google";
import "./globals.css";
import { ThemeContextProvider } from "@/components/ThemeContext";
import Navbar from "@/components/Navbar";

const Vazirmatn_Sans = Vazirmatn({
  subsets: ["arabic"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
  variable: "--font-vazirmatn",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${Vazirmatn_Sans.variable} antialiased`}>
        {/* تم MUI و دارک مود از اینجا کنترل میشه */}
        <ThemeContextProvider>
          {children}
          <Navbar />
        </ThemeContextProvider>
      </body>
    </html>
  );
}
